// Generated by CoffeeScript 1.12.7
var animate, camera, controls, glows, glows_rv, init, mesh, obj_loader, onWindowResize, renderer, scene, texture;

camera = void 0;

scene = void 0;

renderer = void 0;

mesh = void 0;

texture = void 0;

controls = void 0;

glows = [];

glows_rv = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(function() {
  return (Math.random() - Math.random()) / 100.0;
});

obj_loader = function(mat) {
  var loader, manager;
  manager = new THREE.LoadingManager();
  manager.onProgress = function(i, l, p) {
    return console.log(i, l, p);
  };
  loader = new THREE.OBJLoader(manager);
  return loader.load("img/drop.obj", function(obj) {
    obj.scale.set(50.0, 50.0, 50.0);
    obj.traverse(function(c) {
      console.log(c);
      if (c instanceof THREE.Mesh) {
        return c.material = mat;
      }
    });
    scene.add(obj);
    obj.material = mat;
    return mesh = obj;
  });
};

init = function() {
  var background, cubeTexture, glowMat, glowSpr, glowTex, i, j, k, material, pointLight, rr, s, tl;
  camera = new THREE.PerspectiveCamera(70, window.innerWidth / window.innerHeight, 1, 1000);
  camera.position.z = 400;
  controls = new THREE.OrbitControls(camera);
  background = new THREE.Color(0xFA953C);
  scene = new THREE.Scene;
  scene.background = background;
  tl = new THREE.TextureLoader;
  cubeTexture = new THREE.CubeTextureLoader().setPath('img/').load(['posx.jpg', 'negx.jpg', 'posy.jpg', 'negy.jpg', 'posz.jpg', 'negz.jpg']);
  cubeTexture.mapping = THREE.CubeRefractionMapping;
  cubeTexture.format = THREE.RGBFormat;
  glowTex = tl.load("img/glow.png");
  glowMat = new THREE.SpriteMaterial({
    map: glowTex,
    color: 0x555555,
    blending: THREE.AdditiveBlending
  });
  glowSpr = new THREE.Sprite(glowMat);
  glowSpr.scale.set(200.0, 200.0, 1.0);
  scene.add(glowSpr);
  for (i = j = 0; j <= 10; i = ++j) {
    glowMat = new THREE.SpriteMaterial({
      map: glowTex,
      color: 0x202020,
      blending: THREE.AdditiveBlending,
      rotation: Math.random() * 3.141 * 2.0
    });
    glows.push(glowMat);
    glowSpr = new THREE.Sprite(glowMat);
    glowSpr.scale.set(200.0 + Math.random() * 100.0, 10.0 + Math.random() * 20, 1.0);
    scene.add(glowSpr);
  }
  glowMat = new THREE.SpriteMaterial({
    map: glowTex,
    color: 0x202020,
    blending: THREE.AdditiveBlending
  });
  rr = function() {
    return Math.random() - Math.random();
  };
  for (i = k = 0; k <= 100; i = ++k) {
    s = Math.random() * 200.0 + 10.0;
    glowSpr = new THREE.Sprite(glowMat);
    glowSpr.position.set(rr(), rr(), rr());
    glowSpr.position.normalize();
    glowSpr.position.multiplyScalar(500.0);
    glowSpr.scale.set(s, s, 1.0);
    scene.add(glowSpr);
  }
  pointLight = new THREE.PointLight(0xffffff, 2);
  pointLight.position.set(500, 500, 1000);
  scene.add(pointLight);
  pointLight = new THREE.PointLight(0xFF9933, 2);
  pointLight.position.set(-500, -500, 100);
  scene.add(pointLight);
  material = new THREE.MeshPhongMaterial({
    color: 0xDA751C,
    envMap: cubeTexture,
    reflectivity: 0.5,
    combine: THREE.MixOperation
  });
  obj_loader(material);
  renderer = new THREE.WebGLRenderer({
    antialias: true
  });
  renderer.setPixelRatio(window.devicePixelRatio);
  renderer.setSize(window.innerWidth, window.innerHeight);
  document.body.appendChild(renderer.domElement);
  return window.addEventListener('resize', onWindowResize, false);
};

onWindowResize = function() {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
};

animate = function() {
  var g, i, j, len;
  requestAnimationFrame(animate);
  if (controls != null) {
    controls.update();
  }
  for (i = j = 0, len = glows.length; j < len; i = ++j) {
    g = glows[i];
    g.rotation += glows_rv[i];
  }
  renderer.render(scene, camera);
};

init();

animate();
